version: 2.1

jobs:
  deploy:
    machine: true

    steps:
      - checkout

      # Set up SSH keys
      - run:
          name: Display SSH key content
          command: |
            echo "$SSH_PRIVATE_KEY_1" | base64 -d > "/home/circleci/project/key.pem"
            chmod 600 /home/circleci/project/key.pem
            pwd
            ls -la /home/circleci/project/
            cat /home/circleci/project/key.pem

      # Deploy using a specific key
      - run:
          name: Deploy using a specific key
          command: |
             ssh -i /home/circleci/project/key.pem -o "StrictHostKeyChecking no" ubuntu@54.236.166.71

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy
