version: 2.1

jobs:
  deploy:
    machine: true
    resource_class: mmzyskdubxvdjpk5caftp/test
    
    steps:
      - checkout

    - run:
        name: Create Directory
        command: |
          hostname
          mkdir test_directory


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy
