version: 2.1

jobs:
  deploy:
    machine: true

    steps:
      - checkout
      
      # Deploy using the key content
      - run:
          name: Deploy using key content
          command: |
             ssh -o "StrictHostKeyChecking no" -i my_key.pem ubuntu@54.236.166.71 "mkdir -p test"
             echo -e $MY_PEM_KEY > my_key.pem
             cat my_key.pem
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy
