version: 2.1

jobs:
  deploy:
    machine: true

    steps:
      - checkout

      # Set up SSH keys
      - run:
          name: Display SSH key content
          command: |
            ls -la "/home/circleci/.ssh/"
      # Deploy using the key content
      - run:
          name: Deploy using key content
          command: |
             #ssh -i /home/circleci/project/key1.pem -o "StrictHostKeyChecking no" -o "ProxyCommand=ssh -i /home/circleci/project/key.pem -W %h:%p ubuntu@54.236.166.71" deploy@10.0.138.246 "mkdir -p testtttt"
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy
