version: 2.1

jobs:
  deploy:
    machine: true

    steps:
      - checkout

      # Set up SSH keys
      - run:
          name: Display SSH key content
          command: |
            echo "$SSH_PRIVATE_KEY_1"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy
