version: 2.1

jobs:
  deploy:
    machine: true
    resource_class: mmzyskdubxvdjpk5caftp/test
    
    steps:
      - checkout
      
      - run:
          name: Print Hostname
          command: |
            hostname
            cd /home/ubuntu
            pwd
            ssh -o StrictHostKeyChecking=no deploy@10.0.138.246 "echo 'Deploying application'"
 
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy
