version: 2.1

jobs:
  deploy:
    machine: true

    steps:
      - checkout

      # Set up SSH keys
      - run:
          name: Display SSH key content
          command: |
            echo "$SSH_PRIVATE_KEY_1" > "/home/circleci/key.pem"
            chmod 400 /home/circleci/key.pem
            ssh-add "/home/circleci/key.pem"
            ls -la /home/cicleci/
            cat "/home/circleci/key.pem"


      # Deploy using a specific key
      - run:
          name: Deploy using a specific key
          command: |
            ssh -i /home/circleci/key.pem -o "StrictHostKeyChecking no" ubuntu@54.236.166.71

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy
