version: 2.1

jobs:
  deploy:
    machine: true

    steps:
      - checkout

      # Set up SSH keys
      - run:
          name: Display SSH key content
          command: |
            echo "$SSH_PRIVATE_KEY_1" > "$HOME/.ssh/key11.pem"
            chmod 400 /home/circleci/.ssh/key11.pem
            who
            # Add keys to the SSH agent
            eval "$(ssh-agent -s)"
            ssh-add "$HOME/.ssh/key11.pem"

      # Deploy using a specific key
      - run:
          name: Deploy using a specific key
          command: |
            ssh -i /home/circleci/.ssh/key11.pem -o "StrictHostKeyChecking no" -o ubuntu@54.236.166.71

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy
