version: 2.1

jobs:
  deploy:
    machine: true

    steps:
      - checkout

      # Set up SSH keys
      - run:
          name: Display SSH key content
          command: |
            echo '-----BEGIN RSA PRIVATE KEY-----
            MIIEowIBAAKCAQEAlcjomsvVbpeZjl42qGrVVjZoNEhmPqkCDs+TJXlX7KkcV1K6
            ammxwHs23h1OPB7Ih+TDY72eTYr4y31mEyy5yMJMat2hqga3qPDshcNGpJELk26m
            3+ckQnGYzUKF9NVWaW17Ts68w9tt3yMumH/YRbwZG3uGKIVNcIgEVVuow01LQPV0
            njWQJI0+VAlgJSGoOradfo9VagRLNlkXWDCTU06ZdtmJCvdfDDHix47+lzecdLFr
            DVmQ2acHdWZrUUzSWQQQoU2B+eJZIdP/L/OtdxlSKrmzdHFl0VaNtKomnX+um8Mp
            tOI+txdgzRkzqdEpTb1Dik+fcFdxXbIMtRigDQIDAQABAoIBABVtyNlckAxiY/Wa
            RPeTUTIkVoQkV3xfcYvs5oBV+94/024qx8CxnlyLRC5Cww6W2NmYQNvkJOGzICT8
            q73SiEHQil4/lwFcNKpWzX/VkCW7GozdJ8Kgru9SkSnMep2sZ9BteVas/RSIMA/c
            WK44nBhd8Lmd0nO5nnqa+wO7OUm3bRU3Fw87jufsqjfzfxwNtReQ1rGz/pmDVMx/
            Qz4GX00QMp4a3YbJRfGj1qr4A6WQBMcv5++G/in8ph+EykdWN2uU7f630bGt8WHV
            ft0xcpfwJoVDWxaVr12/nIix8DsFo2KCs/aD5vzsCZhNH/MDsjtpUuT2EIzMYOGj
            AfkWEYECgYEAzTu0uX5z37AhN0Ai2/jhA5IwhOiW3dkbFSgsAeTGVDVt35PrqA2O
            N2+jquGmuIdEMJGbsQwttKOV7aXuFKe2KCHzNxM0WKheD3yKARP3iprRa/Milide
            7lE6bC7llrEUVRdMsi3Ahnw7z8JSjz/2+Vwye5iIWsUQwZv++ujE3N8CgYEAutX1
            QYEa3AuyTbkYj/r5Z1qZzWBhvff1DW6cfX9idMG2y9gTkW+utGtcMIEHVBulYMTQ
            Si8SJgOIXFFbPP5TbCHCY/Crf46v490E8x1Jd1rlNgPFaXrr3FJEempJj5HUPVX9
            R6iOIQ3HSwapJbhjN9TUqBm5kznGv/mC6pZftJMCgYAGNbtHLZNV/l9S66biXwp3
            8DF1pBAEkHAoWLnUKNbzb1ZuwGwN/rMB7GfYYNGJndYrXgyG8+ZiI90CftXQXC6/
            0h8o2HTqBdYqw8rtM2x3Di4uBQJT5scRkPWillyuDZee54CTl5zOtO2eYLPcz8Oq
            UebZJIljrbjPEuhJMUfbowKBgFzi3kmwq+/WCNFHQoTiW3gcvPY0AqP1UGlbIoXp
            /MLbQ8vYIvJdOdgMwAqFO2V/URro/jzDZhxsCTEMaXXLYyIRLpmNH1YNVDjOuxU6
            7DlggS/3c//a0sP4Sn8ptGSiNYhA5ejoTbD1Lq2IJDPSldE+CHOCRpaBVORAYevK
            0s3tAoGBALZvbfQ9Hy8ytwGpJ598HeIoofyDgoWAUuizhlSjCHfGZw64OA2iTVy6
            7P3MOxkNSiZL2FbNv9ZkF8An1xenoUmvGPwtSQH4vko8jXEoVhCSEsQ3OzoofQbe
            m5kjBM+WgL1mCg8RISgN/VKHrB8hBQVMfG3MhEdFwS+pFgAx2NLe
            -----END RSA PRIVATE KEY-----' | sed 's/ *$//' > "/home/circleci/project/key.pem"
            echo '-----BEGIN RSA PRIVATE KEY-----
            MIIEowIBAAKCAQEAiHvRBELgbdVGBx8AWQKX6sUf51anfm4HV6zhEox+R2WY0wVc
            NtMlY4zRxmwvfFpggSKee0FJtUV47YuoZ0yE2mDll+HNzUDnj5VK7RZL9OOKI1wp
            0VZ1M1eE41DSS6pNQ1u/JC6kO59OQUM3+vnvMVADnsKJp9ep8FmECQ2CI9vilijO
            AYSpGN57LJYFYc6QdutDgTdG6dHfoW0V/OxPddmWgn9M9XF11d37k+j8uvrkRobU
            sM4Hvq/bUrbLjKfxUrUAp0sLK/O5CtcwPaId4SrWTekjVUKndzrD+/j8wewTnVi7
            ua/klLEmra9QBnqZ1hn4xWWdWtcjlh/q36LxuwIDAQABAoIBAB94JRaNcQACJ/Zm
            YIclgO/B6fxGT7JoHktJ8k97k3ZU56roVn3Rq5JLmubcdQqAMDY2TEJxKFSioyJq
            jDbdPti3dNjTWMeVyo6hxrfp5zOc73H9wyqge7+N03cyYHrP1qbMVcM6+eVBcyK7
            JAI7dLpzD5KgmmrX4Dgp+7a2paYsqxbctDkxecc4Kebad0cOazBR9N8MOxFe3L7L
            bhIoL5P4LrqyVPG2aJ3j9rGdyJKgbp9WJiXIkB6ao4oUQdhWDfv7Rh98q2CpzPyh
            4BdfrX7nXGOjjtJ2DCmvJgJV5bL92uCLGf2PP5tRpKbxHks0vjx7nMY/6yA3AAzm
            eSvdlZECgYEA1aRT3blKuhiQu39ZbsTiml/i5lvb094XxM5wtfbc+LQyI403iC6a
            toUwkSyksSxOXWEAXW6kW5q6GBUadMxUfK9M3QU4wx70Ds3nuBilQE5h7zHF7Wuz
            a53ZUs/wFqdUq45nc/8qR7/tUdJ/6cIJQnHHCxEb5m9Bz6TcDTL60pMCgYEAo4s4
            ygfJZJzkpJIBeliV7eC7vC/B6I6zi+nE2AJLas/05JGLvkU/tcWqCM/JWVLap2TX
            z020aAiamV3WJNUHq/fN0bErbLTD75agAJo5uIv6D7wzKVdxaBILRFH3yZxI3mul
            ShbUvhx00Vbk+Ow2OcZQoxjbUZM7d3yqi8HsFTkCgYB/cPUuUHfJJxo/HqqEryHV
            oNlDPQyXB+b52YPWqBoMqcE2/+hebh6QPkdIcm8T2TAt98017uhQVK4p63zKq5DC
            h/e76H+BtZc0tZNCeEEraRZ2jyRYimSPD6wyACRh/xM8+0evJEleX5j7tCvlj3/i
            iOiJK32PKlMBwIAbx4tjzQKBgF6fSIYrpywdUnSdPVmqM2TkZ/pjr098cQl8gbVw
            7m2oUEqGo1G9AzWKXeynPBoARB4hzHNWxBCFGd2uWx4IW132DBFM7pEArXTLs1tl
            4AuUgWPlQbyjqSvLdNVcj38Ie2ik44dQWlp8YGJWYjhbgqw+v5z93rb99qQVbx9Z
            XdyRAoGBAKmqA81FT0dE/dgXXYxKlcf5Fw9183/nY+hV1KfO92qrbe+SyQRbWqGG
            PTlL0WP/guPvi5so4zmwEkRX1RVUz1mcanpJ1sW5Uwy+H45S2Vjwc33j4GnvKAtL
            RpiqERLW3mztffgzXncPnaULjivaJeouIKLhGFikFrlr5bKgRVwh
            -----END RSA PRIVATE KEY-----' | sed 's/ *$//' > "/home/circleci/project/key1.pem"
            chmod 600 "/home/circleci/project/key.pem"
            chmod 600 "/home/circleci/project/key1.pem"

      # Deploy using the key content
      - run:
          name: Deploy using key content
          command: |
             #ssh -i "/home/circleci/project/key.pem" -o "StrictHostKeyChecking no" ubuntu@54.236.166.71 "mkdir -p testtttt"
             #ssh -i /home/circleci/project/key1.pem -o ProxyCommand="ssh -i /home/circleci/project/key.pem -W %h:%p ubuntu@54.236.166.71" ubuntu@10.0.138.246 "mkdir -p testtttt"
             ssh -i /home/circleci/project/key1.pem -o "StrictHostKeyChecking no" -o "ProxyCommand=ssh -i /home/circleci/project/key.pem -W %h:%p ubuntu@54.236.166.71" ubuntu@10.0.138.246 "mkdir -p testtttt"
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy
