version: 2.1

jobs:
  deploy:
    machine: true

    steps:
      - checkout
            
      - run:
          name: Deploy to Server
          command: |
            ssh -o "StrictHostKeyChecking no" -o "ProxyCommand=ssh -W %h:%p ubuntu@54.236.166.71" deploy@10.0.138.246  "echo 'Deploying application'"
            # ssh -o "StrictHostKeyChecking no" ubuntu@54.236.166.71 "echo 'Deploying application'"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy
