version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    machine: true
    resource_class: mmzyskdubxvdjpk5caftp/test
    steps:
      - run: echo "Hi I'm on Runners!"
