version: 2.1

jobs:
  deploy:
    machine: true
    resource_class: mmzyskdubxvdjpk5caftp/test
    
    steps:
      - checkout
      
      - run:
          name: Print Hostname
          command: |
            hostname
            pwd
            ls -la /home/ubuntu
            cat /home/ubuntu/testt
            mkdir /home/ubuntu/test
 
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy
