version: 2.1

jobs:
  deploy:
    machine: true
    resource_class: mmzyskdubxvdjpk5caftp/test
    
    steps:
      - checkout

      # Add a step to print out the hostname
      - run:
          name: Print Hostname
          command: |
            hostname

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy
