version: 2.1

jobs:
  deploy:
    machine: true

    steps:
      - checkout
      
      # Deploy using the key content
      - run:
          name: Deploy using key content
          command: |
             ssh -o "StrictHostKeyChecking no" -o "ProxyCommand=ssh -W %h:%p ubuntu@54.236.166.71" deploy@10.0.138.246 "mkdir -p test"
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy
